// client/src/components/custom/CompetitorRankDropdown.vue
<script setup lang="ts">
import { LoaderCircle } from "lucide-vue-next";
import { computed, ref } from "vue";
import type { RankingSnapshot } from "@/lib/types";
import RankingsAreaChart from "@/components/charts/RankingsAreaChart.vue";
import CompetitorLink from "@/components/custom/CompetitorLink.vue";
import DateRangePicker from "@/components/custom/DateRangePicker.vue";
import RankChangeIndicator from "@/components/custom/RankChangeIndicator.vue";
import RotatableChevron from "@/components/custom/RotatableChevron.vue";
import { Button } from "@/components/ui/button";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useRankDetail } from "@/lib/composables/useRankDetail";
import { isTimeEvent } from "@/lib/utils";

const {
  competitor,
  selectedEvent,
  formattedScore,
  rankDate,
  index,
  showRegionRank,
} = defineProps<{
  competitor: RankingSnapshot;
  selectedEvent: string;
  formattedScore: string;
  rankDate: Date;
  index: number;
  showRegionRank?: boolean;
}>();

const isOpen = ref(false);

const {
  selectedDateRange,
  applyDateRange,
  hasCompleteRange,
  metric,
  detailData,
  isPending,
  isFetching,
  error,
  mappedHistory,
} = useRankDetail({
  competitorId: computed(() => competitor.person_id),
  competitorName: computed(() => competitor.name),
  eventId: computed(() => selectedEvent),
  isOpen,
  rankDate: computed(() => rankDate),
});

const ariaId = computed(() => `details-${competitor.person_id}`);
</script>

<template>
  <Collapsible v-model:open="isOpen">
    <CollapsibleTrigger as-child :aria-controls="ariaId">
      <div
        role="button"
        tabindex="0"
        :aria-label="`Details for ${competitor.person_id}`"
        class="flex w-full cursor-pointer justify-between rounded-md border-0 bg-transparent p-2 ps-1 text-left hover:bg-secondary focus:outline-none focus-visible:bg-secondary"
        :class="{ 'bg-muted/20': index % 2 === 0 }"
      >
        <div
          v-if="showRegionRank && competitor.sub_rank"
          class="w-16 shrink-0 ps-3 text-left text-xs sm:text-sm md:w-28"
        >
          <span>{{ competitor.sub_rank.rank }}</span>
          <RankChangeIndicator :change="competitor.sub_rank.rank_change" />
        </div>
        <div class="w-20 shrink-0 ps-3 text-left text-foreground md:w-28">
          <span>{{ competitor.global_rank.current }}</span>
          <RankChangeIndicator :change="competitor.global_rank.change" />
        </div>
        <div class="min-w-0 flex-2 text-left">
          <CompetitorLink
            :name="competitor.name"
            :id="competitor.person_id"
            :iso2="competitor.country_iso2"
            class="flex flex-row items-center"
          />
        </div>
        <div class="flex-1 pe-3 text-right">
          {{ formattedScore }}
        </div>
        <div class="flex w-6 shrink-0 items-center justify-end">
          <RotatableChevron :up="isOpen" />
        </div>
      </div>
    </CollapsibleTrigger>

    <CollapsibleContent class="space-y-2" :id="ariaId">
      <div v-if="isPending" class="flex justify-center py-4">
        <LoaderCircle class="h-6 w-6 animate-spin text-muted-foreground" />
      </div>

      <div
        v-else-if="error"
        class="mt-2 py-4 text-center text-sm text-destructive"
      >
        {{ error.message }}
      </div>

      <div v-if="detailData?.length > 0" class="relative px-4 py-2">
        <div
          v-if="isFetching && !isPending"
          class="absolute inset-0 z-10 flex items-center justify-center rounded-md bg-background/50"
        >
          <LoaderCircle class="h-6 w-6 animate-spin text-muted-foreground" />
        </div>

        <RankingsAreaChart
          :history="mappedHistory"
          :stacked="false"
          :metric="metric"
          :isTime="isTimeEvent(selectedEvent)"
          :isFMC="selectedEvent === '333fm'"
        />
      </div>

      <div
        v-else-if="
          detailData && Array.isArray(detailData) && detailData.length === 0
        "
        class="py-4 text-center text-sm text-muted-foreground"
      >
        No history available.
      </div>

      <div class="ms-4 flex items-center gap-2 pb-2">
        <Select v-model="metric">
          <SelectTrigger class="w-32 text-xs">
            <SelectValue placeholder="Select Metric" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="value">Result</SelectItem>
            <SelectItem value="rank">Rank</SelectItem>
          </SelectContent>
        </Select>

        <DateRangePicker
          v-model:start-date="selectedDateRange.start"
          v-model:end-date="selectedDateRange.end"
          :allow-future="false"
        />

        <Button
          size="sm"
          :disabled="isFetching || !hasCompleteRange"
          @click="applyDateRange"
        >
          Update
        </Button>
      </div>

      <hr class="mx-2" />
    </CollapsibleContent>
  </Collapsible>
</template>

// client/src/components/custom/CompetitorRankDropdown.tsx
import type { RankingSnapshot } from "../../lib/types";
import { createSignal, Show, Switch, Match } from "solid-js";
import { Collapsible } from "@kobalte/core/collapsible";
import { LoaderCircle } from "lucide-solid";
import { useRankDetail } from "../../lib/useRankDetail";
import { cn, isTimeEvent } from "../../lib/utils";
import { Button } from "../ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../ui/select";
import { CompetitorLink } from "./CompetitorLink";
import { DateRangePicker } from "./DateRangePicker";
import { RankChangeIndicator } from "./RankChangeIndicator";
import { RankingsAreaChart } from "./RankingsAreaChart";
import { RotatableChevron } from "./RotatableChevron";

interface CompetitorRankDropdownProps {
  competitor: RankingSnapshot;
  selectedEvent: string;
  formattedScore: string;
  rankDate: Date;
  index: number;
  showRegionRank?: boolean;
}

export function CompetitorRankDropdown(props: CompetitorRankDropdownProps) {
  const [isOpen, setIsOpen] = createSignal(false);

  const {
    startDate,
    setStartDate,
    endDate,
    setEndDate,
    applyDateRange,
    hasCompleteRange,
    metric,
    setMetric,
    query,
    mappedHistory,
  } = useRankDetail({
    competitorId: () => props.competitor.person_id,
    competitorName: () => props.competitor.name,
    eventId: () => props.selectedEvent,
    isOpen,
    rankDate: () => props.rankDate,
  });

  const ariaId = () => `details-${props.competitor.person_id}`;

  return (
    <Collapsible open={isOpen()} onOpenChange={setIsOpen}>
      <Collapsible.Trigger
        aria-controls={ariaId()}
        class={cn(
          "flex w-full cursor-pointer justify-between rounded-md border-0 bg-transparent p-2 ps-1 text-left text-sm hover:bg-secondary focus:outline-none focus-visible:bg-secondary",
          props.index % 2 === 0 && "bg-muted/20",
        )}
      >
        <Show when={props.showRegionRank && props.competitor.sub_rank}>
          <div class="flex w-16 shrink-0 items-center gap-1 ps-3 text-left text-xs sm:text-sm md:w-28">
            <span>{props.competitor.sub_rank!.rank}</span>
            <RankChangeIndicator change={props.competitor.sub_rank!.rank_change} />
          </div>
        </Show>
        <div class="flex w-20 shrink-0 items-center gap-1 ps-3 text-left text-foreground md:w-28">
          <span>{props.competitor.global_rank.current}</span>
          <RankChangeIndicator change={props.competitor.global_rank.change} />
        </div>
        <div class="min-w-0 flex-2 text-left">
          <CompetitorLink
            name={props.competitor.name}
            id={props.competitor.person_id}
            iso2={props.competitor.country_iso2}
            class="flex flex-row items-center"
          />
        </div>
        <div class="flex-1 pe-3 text-right">{props.formattedScore}</div>
        <div class="flex w-6 shrink-0 items-center justify-end">
          <RotatableChevron up={isOpen()} />
        </div>
      </Collapsible.Trigger>

      <Collapsible.Content
        class="space-y-2 overflow-hidden duration-100 ease-out animate-in fade-in-0"
        id={ariaId()}
      >
        <Switch
          fallback={
            <div class="py-4 text-center text-sm text-muted-foreground">No history available.</div>
          }
        >
          <Match when={query.isPending}>
            <div class="flex justify-center py-4">
              <LoaderCircle class="h-6 w-6 animate-spin text-muted-foreground" />
            </div>
          </Match>

          <Match when={query.isError}>
            <div class="mt-2 py-4 text-center text-sm text-destructive">{query.error?.message}</div>
          </Match>

          <Match when={query.data && Array.isArray(query.data) && query.data.length > 0}>
            <div class="relative px-4 py-2">
              <Show when={query.isFetching}>
                <div class="absolute inset-0 z-10 flex items-center justify-center rounded-md bg-background/50">
                  <LoaderCircle class="h-6 w-6 animate-spin text-muted-foreground" />
                </div>
              </Show>

              <RankingsAreaChart
                history={mappedHistory()}
                metric={metric()}
                isTime={isTimeEvent(props.selectedEvent)}
                isFMC={props.selectedEvent === "333fm"}
              />
            </div>
          </Match>
        </Switch>

        <div class="ms-4 flex items-center gap-2 pb-2">
          <Select
            options={["value", "rank"]}
            value={metric()}
            onChange={(val) => {
              if (val) {
                setMetric(val as any);
              }
            }}
            itemComponent={(itemProps) => (
              <SelectItem item={itemProps.item}>
                {itemProps.item.rawValue === "value" ? "Result" : "Rank"}
              </SelectItem>
            )}
          >
            <SelectTrigger class="h-9 w-32 text-xs">
              <SelectValue>
                {(state) => (state.selectedOption() === "value" ? "Result" : "Rank")}
              </SelectValue>
            </SelectTrigger>
            <SelectContent />
          </Select>

          <DateRangePicker
            startDate={startDate()}
            onStartDateChange={setStartDate}
            endDate={endDate()}
            onEndDateChange={setEndDate}
            allowFuture={false}
          />

          <Button
            size="sm"
            disabled={query.isFetching || !hasCompleteRange()}
            onClick={applyDateRange}
            class="h-9 px-3"
          >
            Update
          </Button>
        </div>

        <hr class="mx-2" />
      </Collapsible.Content>
    </Collapsible>
  );
}
