// client/src/components/custom/CompetitorList.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type {
  CompetitorSimulationResult,
  SupportedWCAEvent,
} from "@/lib/types";
import CompetitorDropdown from "./CompetitorDropdown.vue";
import Chevron from "./RotatableChevron.vue";

type sortCol = "name" | "win" | "pod" | "rank";

interface groupedResults {
  idx: number;
  results: CompetitorSimulationResult;
  color: string;
}

const { simulationResults, colors, event } = defineProps<{
  simulationResults: CompetitorSimulationResult[];
  colors: string[];
  event: SupportedWCAEvent;
}>();

const sortBy = ref<sortCol>("win");
const sortAsc = ref<boolean>(false);

const headerOptions = [
  {
    flex: "flex-[2] lg:flex-[1.5]",
    id: "name",
    justify: "justify-start",
    label: "Name",
    padding: "ps-8",
  },
  {
    flex: "flex-1",
    id: "win",
    justify: "justify-center",
    label: "Chance of winning",
    padding: "",
  },
  {
    flex: "flex-1",
    id: "pod",
    justify: "justify-center",
    label: "Chance of podiuming",
    padding: "",
  },
  {
    flex: "flex-1",
    id: "rank",
    justify: "justify-center",
    label: "Expected rank",
    padding: "",
  },
] as const;

const setSortBy = (col: sortCol) => {
  if (sortBy.value === col) {
    sortAsc.value = !sortAsc.value;
  } else {
    sortBy.value = col;
    sortAsc.value = false;
  }
};

const groupedProps = computed(() => {
  const getSortValue = (item: groupedResults): number | string => {
    switch (sortBy.value) {
      case "name":
        return item.results.name;
      case "win":
        return item.results.win_chance;
      case "pod":
        return item.results.pod_chance;
      case "rank":
        return item.results.expected_rank;
    }
  };

  const sortFn = (a: groupedResults, b: groupedResults) => {
    const aVal = getSortValue(a);
    const bVal = getSortValue(b);

    const comparison =
      typeof aVal === "string" && typeof bVal === "string"
        ? aVal.localeCompare(bVal)
        : (aVal as number) - (bVal as number);

    // For stats (win/pod), higher is better so default descending;
    // for rank, lower is better so also default descending (shows best first).
    // Name sorts alphabetically ascending by default.
    const defaultAsc = sortBy.value === "name" || sortBy.value === "rank";
    const effectiveAsc = defaultAsc ? !sortAsc.value : sortAsc.value;
    return effectiveAsc ? comparison : -comparison;
  };

  return simulationResults
    .map((results, idx) => ({
      color: colors[idx],
      idx,
      results,
    }))
    .toSorted(sortFn);
});

const model = defineModel<number[][]>({ required: true });
</script>

<template>
  <div class="mt-2 rounded-md border">
    <div class="me-8 flex justify-between p-1">
      <button
        v-for="option in headerOptions"
        :key="option.id"
        @click="setSortBy(option.id)"
        :class="[
          'flex items-center',
          option.padding,
          option.flex,
          option.justify,
        ]"
      >
        <span>{{ option.label }}</span>
        <Chevron
          v-show="sortBy === option.id"
          class="ms-1"
          :up="!sortAsc"
          :animate="false"
        />
      </button>
    </div>
    <hr class="mx-2" />
    <ol class="space-y-0.5 p-1">
      <li v-for="person in groupedProps" :key="person.results.id">
        <CompetitorDropdown
          v-model="model[person.idx]"
          :result="person.results"
          :event="event"
          :color="person.color"
        />
      </li>
    </ol>
  </div>
</template>

// client/src/components/custom/CompetitorList.tsx
import type { CompetitorSimulationResult, SupportedWCAEvent } from "../../lib/types";
import { createSignal, createMemo, For, Show } from "solid-js";
import { CompetitorDropdown } from "./CompetitorDropdown";
import { RotatableChevron } from "./RotatableChevron";

type sortCol = "name" | "win" | "pod" | "rank";

interface GroupedResults {
  idx: number;
  results: CompetitorSimulationResult;
  color: string;
}

interface CompetitorListProps {
  simulationResults: CompetitorSimulationResult[];
  colors: string[];
  event: SupportedWCAEvent;
  value: number[][];
  onChange: (val: number[][]) => void;
}

export function CompetitorList(props: CompetitorListProps) {
  const [sortBy, setSortBy] = createSignal<sortCol>("win");
  const [sortAsc, setSortAsc] = createSignal<boolean>(false);
  const [expandedIds, setExpandedIds] = createSignal<Set<string>>(new Set());

  const toggleExpanded = (id: string) => {
    const next = new Set(expandedIds());
    if (next.has(id)) {
      next.delete(id);
    } else {
      next.add(id);
    }
    setExpandedIds(next);
  };

  const headerOptions = [
    {
      flex: "flex-[2] lg:flex-[1.5]",
      id: "name" as sortCol,
      justify: "justify-start",
      label: "Name",
      padding: "ps-8",
    },
    {
      flex: "flex-1",
      id: "win" as sortCol,
      justify: "justify-center",
      label: "Chance of winning",
      padding: "",
    },
    {
      flex: "flex-1",
      id: "pod" as sortCol,
      justify: "justify-center",
      label: "Chance of podiuming",
      padding: "",
    },
    {
      flex: "flex-1",
      id: "rank" as sortCol,
      justify: "justify-center",
      label: "Expected rank",
      padding: "",
    },
  ] as const;

  const handleSort = (col: sortCol) => {
    if (sortBy() === col) {
      setSortAsc(!sortAsc());
    } else {
      setSortBy(col);
      setSortAsc(false);
    }
  };

  const groupedProps = createMemo(() => {
    const getSortValue = (item: GroupedResults): number | string => {
      switch (sortBy()) {
        case "name":
          return item.results.name;
        case "win":
          return item.results.win_chance;
        case "pod":
          return item.results.pod_chance;
        case "rank":
          return item.results.expected_rank;
        default:
          return 0;
      }
    };

    const sortFn = (a: GroupedResults, b: GroupedResults) => {
      const aVal = getSortValue(a);
      const bVal = getSortValue(b);

      const comparison =
        typeof aVal === "string" && typeof bVal === "string"
          ? aVal.localeCompare(bVal)
          : (aVal as number) - (bVal as number);

      const defaultAsc = sortBy() === "name" || sortBy() === "rank";
      const effectiveAsc = defaultAsc ? !sortAsc() : sortAsc();
      return effectiveAsc ? comparison : -comparison;
    };

    return props.simulationResults
      .map((results, idx) => ({
        color: props.colors[idx],
        idx,
        results,
      }))
      .toSorted(sortFn);
  });

  return (
    <div class="mt-2 rounded-md border text-card-foreground">
      <div class="me-8 flex justify-between p-1">
        <For each={headerOptions}>
          {(option) => (
            <button
              onClick={() => {
                handleSort(option.id);
              }}
              class={`flex cursor-pointer items-center ${option.padding} ${option.flex} ${option.justify}`}
            >
              <span>{option.label}</span>
              <Show when={sortBy() === option.id}>
                <span class="ms-1">
                  <RotatableChevron up={!sortAsc()} animate={false} />
                </span>
              </Show>
            </button>
          )}
        </For>
      </div>
      <hr class="mx-2 border-border" />
      <ol class="space-y-0.5 p-1">
        <For each={groupedProps()}>
          {(person) => (
            <li>
              <CompetitorDropdown
                value={props.value[person.idx] || []}
                onChange={(updatedRow) => {
                  const updated = [...props.value];
                  updated[person.idx] = updatedRow;
                  props.onChange(updated);
                }}
                result={person.results}
                event={props.event}
                color={person.color}
                isOpen={expandedIds().has(person.results.id)}
                onToggle={() => {
                  toggleExpanded(person.results.id);
                }}
              />
            </li>
          )}
        </For>
      </ol>
    </div>
  );
}
