// client/src/components/custom/CountryFilterButton.vue
<script setup lang="ts">
import { useQuery } from "@tanstack/vue-query";
import { useVirtualizer } from "@tanstack/vue-virtual";
import { Check, ChevronDown, Globe, Search, X } from "lucide-vue-next";
import { computed, nextTick, ref, watch } from "vue";
import type { CountryResult } from "@/lib/types";
import FlagIcon from "@/components/custom/FlagIcon.vue";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { API_URL } from "@/lib/utils";

const { modelValue, includeRegions = false } = defineProps<{
  modelValue: CountryResult | undefined;
  includeRegions?: boolean;
}>();

const emit = defineEmits<{
  "update:modelValue": [value: CountryResult | undefined];
}>();

const open = ref(false);
const search = ref("");
const listRef = ref<HTMLDivElement | undefined>(undefined);
const inputRef = ref<HTMLInputElement | undefined>(undefined);

const { data: countries } = useQuery({
  queryFn: async () => {
    const res = await fetch(
      `${API_URL}/api/countries?include_regions=${includeRegions}`,
    );
    return res.json() as Promise<CountryResult[]>;
  },
  queryKey: [
    "countries",
    {
      include_regions: includeRegions,
    },
  ],
  staleTime: Infinity,
});

// Split countries into "special" (World + continents) and real countries
const specialEntries = computed(
  () =>
    countries.value?.filter((c) => c.id === "World" || c.id.startsWith("_")) ??
    [],
);
const realCountries = computed(
  () =>
    countries.value?.filter((c) => c.id !== "World" && !c.id.startsWith("_")) ??
    [],
);

// Filter based on search
const filteredSpecial = computed(() => {
  if (!search.value) return specialEntries.value;
  const q = search.value.toLowerCase();
  return specialEntries.value.filter((c) => c.name.toLowerCase().includes(q));
});
const filteredCountries = computed(() => {
  if (!search.value) return realCountries.value;
  const q = search.value.toLowerCase();
  return realCountries.value.filter((c) => c.name.toLowerCase().includes(q));
});

// Build a flat list with group headers for the virtualizer
type ListEntry =
  | { type: "header"; label: string }
  | { type: "separator" }
  | { type: "item"; country: CountryResult };

const flatList = computed<ListEntry[]>(() => {
  const entries: ListEntry[] = [];
  if (filteredSpecial.value.length > 0) {
    entries.push({ label: "Regions", type: "header" });
    for (const c of filteredSpecial.value) {
      entries.push({ country: c, type: "item" });
    }
  }
  if (filteredSpecial.value.length > 0 && filteredCountries.value.length > 0) {
    entries.push({ type: "separator" });
  }
  if (filteredCountries.value.length > 0) {
    entries.push({ label: "Countries", type: "header" });
    for (const c of filteredCountries.value) {
      entries.push({ country: c, type: "item" });
    }
  }
  return entries;
});

function getCountry(index: number): CountryResult {
  return (flatList.value[index] as { type: "item"; country: CountryResult })
    .country;
}

const virtualizer = useVirtualizer({
  get count() {
    return flatList.value.length;
  },
  estimateSize: (index) => {
    const entry = flatList.value[index];
    if (entry.type === "header") return 26;
    if (entry.type === "separator") return 9;
    return 36;
  },
  getScrollElement: () => listRef.value ?? null,
  measureElement: (el) => el.getBoundingClientRect().height,
  overscan: 5,
});

// Auto-focus search input when popover opens
watch(open, async (isOpen) => {
  if (isOpen) {
    search.value = "";
    await nextTick();
    inputRef.value?.focus();
  }
});

// Keyboard navigation
const highlightedIndex = ref(-1);

watch(flatList, () => {
  highlightedIndex.value = -1;
});

function findNextItemIndex(from: number, direction: 1 | -1): number {
  let i = from;
  while (i >= 0 && i < flatList.value.length) {
    if (flatList.value[i].type === "item") return i;
    i += direction;
  }
  return -1;
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === "ArrowDown") {
    e.preventDefault();
    const next = findNextItemIndex(highlightedIndex.value + 1, 1);
    if (next !== -1) {
      highlightedIndex.value = next;
      virtualizer.value.scrollToIndex(next, { align: "auto" });
    }
  } else if (e.key === "ArrowUp") {
    e.preventDefault();
    const prev = findNextItemIndex(highlightedIndex.value - 1, -1);
    if (prev !== -1) {
      highlightedIndex.value = prev;
      virtualizer.value.scrollToIndex(prev, { align: "auto" });
    }
  } else if (e.key === "Enter") {
    e.preventDefault();
    const entry = flatList.value[highlightedIndex.value];
    if (entry?.type === "item") {
      select(entry.country);
    }
  }
}

const select = (country: CountryResult) => {
  if (country.id === "World") {
    emit("update:modelValue", undefined);
  } else {
    emit("update:modelValue", country);
  }
  open.value = false;
};

const clear = (e: MouseEvent) => {
  e.stopPropagation();
  emit("update:modelValue", undefined);
};
</script>

<template>
  <Popover v-model:open="open">
    <PopoverTrigger as-child>
      <Button
        variant="outline"
        role="combobox"
        :aria-expanded="open"
        class="w-40 justify-between gap-2 font-normal"
        id="country-filter-btn"
      >
        <span class="flex items-center gap-2 truncate">
          <template v-if="modelValue">
            <FlagIcon :code="modelValue.iso2" :showTooltip="false" />
            <span class="truncate">{{ modelValue.name }}</span>
          </template>
          <template v-else>
            <Globe class="h-4 w-4 shrink-0 opacity-50" />
            <span>World</span>
          </template>
        </span>
        <span class="flex shrink-0 items-center gap-1">
          <span v-if="modelValue" @click.stop="clear" class="flex items-center">
            <X class="h-3.5 w-3.5 text-muted-foreground hover:text-current" />
          </span>
          <ChevronDown class="h-4 w-4 text-muted-foreground" />
        </span>
      </Button>
    </PopoverTrigger>

    <PopoverContent class="w-64 p-0">
      <div
        class="flex h-full w-full flex-col overflow-hidden rounded-md bg-popover text-popover-foreground"
      >
        <!-- Search input -->
        <div class="flex items-center border-b px-3">
          <Search class="mr-2 h-4 w-4 shrink-0 opacity-50" />
          <input
            ref="inputRef"
            v-model="search"
            placeholder="Search countries..."
            id="country-filter-input"
            class="flex h-10 w-full rounded-md bg-transparent py-3 text-sm outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50"
            @keydown="onKeydown"
          />
        </div>

        <!-- Empty state -->
        <div
          v-if="flatList.length === 0"
          class="py-6 text-center text-sm text-muted-foreground"
        >
          No countries found.
        </div>

        <!-- Virtualized list -->
        <div
          v-else
          ref="listRef"
          class="max-h-75 overflow-x-hidden overflow-y-auto"
        >
          <div
            :style="{
              height: `${virtualizer.getTotalSize()}px`,
              width: '100%',
              position: 'relative',
            }"
          >
            <div
              v-for="row in virtualizer.getVirtualItems()"
              :key="row.index"
              :ref="
                (el) => {
                  if (el) virtualizer.measureElement(el as Element);
                }
              "
              :data-index="row.index"
              :style="{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                transform: `translateY(${row.start}px)`,
              }"
            >
              <!-- Group header -->
              <div
                v-if="flatList[row.index].type === 'header'"
                class="px-3 py-1.5 text-xs font-medium text-muted-foreground"
              >
                {{
                  (flatList[row.index] as { type: "header"; label: string })
                    .label
                }}
              </div>

              <!-- Separator -->
              <div
                v-else-if="flatList[row.index].type === 'separator'"
                class="px-1 py-1"
              >
                <div class="h-px bg-border" />
              </div>

              <!-- Country item -->
              <div
                v-else
                class="relative mx-1 flex cursor-pointer items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none select-none"
                :class="{
                  'bg-accent text-accent-foreground':
                    highlightedIndex === row.index,
                  'hover:bg-accent hover:text-accent-foreground':
                    highlightedIndex !== row.index,
                }"
                @click="select(getCountry(row.index))"
                @mouseenter="highlightedIndex = row.index"
              >
                <Check
                  class="h-4 w-4 shrink-0"
                  :class="
                    modelValue?.id === getCountry(row.index).id ||
                    (getCountry(row.index).id === 'World' && !modelValue)
                      ? 'opacity-100'
                      : 'opacity-0'
                  "
                />
                <Globe
                  v-if="getCountry(row.index).id === 'World'"
                  class="h-4 w-4 opacity-50"
                />
                <FlagIcon
                  v-else-if="!getCountry(row.index).id.startsWith('_')"
                  :code="getCountry(row.index).iso2"
                  :showTooltip="false"
                />
                <span
                  :class="{
                    'ms-6':
                      getCountry(row.index).id !== 'World' &&
                      getCountry(row.index).id.startsWith('_'),
                  }"
                >
                  {{ getCountry(row.index).name }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </PopoverContent>
  </Popover>
</template>

// client/src/components/custom/CountryFilterButton.tsx
import type { CountryResult } from "../../lib/types";
import {
  createSignal,
  createEffect,
  onCleanup,
  For,
  Show,
  Switch,
  Match,
  createMemo,
} from "solid-js";
import { createQuery } from "@tanstack/solid-query";
import { createVirtualizer } from "@tanstack/solid-virtual";
import { Check, ChevronDown, Globe, Search, X } from "lucide-solid";
import { buildUrl, cn } from "../../lib/utils";
import { Popover, PopoverContent, PopoverTrigger } from "../ui/popover";
import { FlagIcon } from "./FlagIcon";

interface CountryFilterButtonProps {
  value: CountryResult | undefined;
  onChange: (value?: CountryResult) => void;
  includeRegions?: boolean;
}

export function CountryFilterButton(props: CountryFilterButtonProps) {
  const [open, setOpen] = createSignal(false);
  const [search, setSearch] = createSignal("");
  // eslint-disable-next-line no-unassigned-vars
  let inputRef: HTMLInputElement | undefined;

  const query = createQuery(() => ({
    queryFn: async () => {
      const res = await fetch(
        buildUrl("/api/countries", { include_regions: props.includeRegions ?? false }),
      );
      return res.json() as Promise<CountryResult[]>;
    },
    queryKey: ["countries", { include_regions: props.includeRegions ?? false }],
    staleTime: Infinity,
  }));

  createEffect(() => {
    if (open()) {
      setSearch("");
      const timer = setTimeout(() => {
        inputRef?.focus();
      }, 0);
      onCleanup(() => {
        clearTimeout(timer);
      });
    }
  });

  const specialEntries = () =>
    query.data?.filter((c) => c.id === "World" || c.id.startsWith("_")) ?? [];

  const realCountries = () =>
    query.data?.filter((c) => c.id !== "World" && !c.id.startsWith("_")) ?? [];

  const filteredSpecial = () => {
    const q = search().trim().toLowerCase();
    if (!q) {
      return specialEntries();
    }
    return specialEntries().filter((c) => c.name.toLowerCase().includes(q));
  };

  const filteredCountries = () => {
    const q = search().trim().toLowerCase();
    if (!q) {
      return realCountries();
    }
    return realCountries().filter((c) => c.name.toLowerCase().includes(q));
  };

  type ListEntry =
    | { type: "header"; label: string }
    | { type: "separator" }
    | { type: "item"; country: CountryResult };

  const flatList = createMemo<ListEntry[]>(() => {
    const entries: ListEntry[] = [];
    const special = filteredSpecial();
    const countries = filteredCountries();

    if (special.length > 0) {
      entries.push({ label: "Regions", type: "header" });
      for (const c of special) {
        entries.push({ country: c, type: "item" });
      }
    }
    if (special.length > 0 && countries.length > 0) {
      entries.push({ type: "separator" });
    }
    if (countries.length > 0) {
      entries.push({ label: "Countries", type: "header" });
      for (const c of countries) {
        entries.push({ country: c, type: "item" });
      }
    }
    return entries;
  });

  const [listRef, setListRef] = createSignal<HTMLDivElement | null>(null);

  const virtualizer = createVirtualizer({
    get count() {
      return flatList().length;
    },
    getScrollElement: () => listRef(),
    estimateSize: (index) => {
      const entry = flatList()[index];
      if (!entry) {
        return 36;
      }
      if (entry.type === "header") {
        return 26;
      }
      if (entry.type === "separator") {
        return 9;
      }
      return 36;
    },
    overscan: 5,
  });

  const select = (country: CountryResult) => {
    if (country.id === "World") {
      props.onChange();
    } else {
      props.onChange(country);
    }
    setOpen(false);
  };

  const clear = (e: MouseEvent) => {
    e.stopPropagation();
    props.onChange();
  };

  return (
    <Popover open={open()} onOpenChange={setOpen} gutter={4}>
      <PopoverTrigger
        class="flex h-9 w-40 items-center justify-between gap-2 rounded-md border border-input bg-background px-3 py-2 text-sm font-normal shadow-sm ring-offset-background"
        id="country-filter-btn"
      >
        <span class="flex min-w-0 items-center gap-2 truncate">
          <Show
            when={props.value}
            fallback={
              <>
                <Globe class="h-4 w-4 shrink-0 opacity-50" />
                <span class="truncate">World</span>
              </>
            }
          >
            {(val) => (
              <>
                <FlagIcon code={val().iso2} showTooltip={false} />
                <span class="truncate">{val().name}</span>
              </>
            )}
          </Show>
        </span>
        <span class="flex shrink-0 items-center gap-1">
          <Show when={props.value}>
            <span onClick={clear} class="flex cursor-pointer items-center">
              <X class="h-3.5 w-3.5 text-muted-foreground hover:text-foreground" />
            </span>
          </Show>
          <ChevronDown class="h-4 w-4 text-muted-foreground" />
        </span>
      </PopoverTrigger>

      <PopoverContent class="w-64 p-0">
        <div class="flex h-full w-full flex-col overflow-hidden rounded-md bg-popover text-popover-foreground">
          {/* Search Input */}
          <div class="flex items-center border-b px-3">
            <Search class="mr-2 h-4 w-4 shrink-0 opacity-50" />
            <input
              ref={(el) => {
                inputRef = el;
              }}
              value={search()}
              onInput={(e) => {
                setSearch(e.currentTarget.value);
              }}
              placeholder="Search countries..."
              id="country-filter-input"
              class="flex h-10 w-full rounded-md bg-transparent py-3 text-sm outline-none placeholder:text-muted-foreground"
            />
          </div>

          {/* List */}
          <div ref={setListRef} class="max-h-75 overflow-x-hidden overflow-y-auto p-1">
            <Show
              when={flatList().length > 0}
              fallback={
                <div class="py-6 text-center text-sm text-muted-foreground">
                  No countries found.
                </div>
              }
            >
              <div
                style={{
                  height: `${virtualizer.getTotalSize()}px`,
                  width: "100%",
                  position: "relative",
                }}
              >
                <For each={virtualizer.getVirtualItems()}>
                  {(row) => {
                    const entry = () => flatList()[row.index];
                    return (
                      <div
                        ref={(el) => {
                          if (el) {
                            virtualizer.measureElement(el);
                          }
                        }}
                        data-index={row.index}
                        style={{
                          position: "absolute",
                          top: 0,
                          left: 0,
                          width: "100%",
                          transform: `translateY(${row.start}px)`,
                        }}
                      >
                        <Switch>
                          <Match when={entry()?.type === "header"}>
                            <div class="px-3 py-1.5 text-xs font-medium text-muted-foreground">
                              {(entry() as { label: string }).label}
                            </div>
                          </Match>
                          <Match when={entry()?.type === "separator"}>
                            <div class="px-1 py-1">
                              <div class="h-px bg-border" />
                            </div>
                          </Match>
                          <Match when={entry()?.type === "item"}>
                            {(() => {
                              const c = (entry() as { country: CountryResult }).country;
                              const isSelected = () =>
                                (!props.value && c.id === "World") ||
                                (props.value !== undefined && props.value.id === c.id);

                              return (
                                <button
                                  onClick={() => {
                                    select(c);
                                  }}
                                  class={cn(
                                    "relative flex w-full cursor-pointer items-center gap-2 rounded-sm px-2 py-1.5 text-left text-sm outline-none select-none hover:bg-accent hover:text-accent-foreground",
                                    isSelected() && "bg-accent/50 text-accent-foreground",
                                  )}
                                >
                                  <Check
                                    class={cn(
                                      "h-4 w-4 shrink-0",
                                      isSelected() ? "opacity-100" : "opacity-0",
                                    )}
                                  />
                                  <Show
                                    when={c.id === "World"}
                                    fallback={<FlagIcon code={c.iso2} showTooltip={false} />}
                                  >
                                    <Globe class="h-4 w-4 opacity-50" />
                                  </Show>
                                  <span>{c.name}</span>
                                </button>
                              );
                            })()}
                          </Match>
                        </Switch>
                      </div>
                    );
                  }}
                </For>
              </div>
            </Show>
          </div>
        </div>
      </PopoverContent>
    </Popover>
  );
}
