// client/src/components/custom/LoadingMessage.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";

const { message } = defineProps<{ message: string }>();

const loadingText = ref(message);
const dots = ref("");
let intervalId: number | undefined;

const updateDots = () => {
  dots.value = dots.value.length < 3 ? `${dots.value}.` : "";
  loadingText.value = `${message}${dots.value}`;
};

onMounted(() => {
  intervalId = window.setInterval(updateDots, 333);
});

onUnmounted(() => {
  clearInterval(intervalId);
});
</script>

<template>
  <div class="text-center text-2xl">
    {{ loadingText }}
  </div>
</template>

// client/src/components/custom/LoadingMessage.tsx
import { createSignal, onMount, onCleanup } from "solid-js";
import { cn } from "../../lib/utils";

interface LoadingMessageProps {
  message: string;
  class?: string;
}

export function LoadingMessage(props: LoadingMessageProps) {
  const [dots, setDots] = createSignal("");
  let intervalId: ReturnType<typeof setInterval> | undefined;

  const updateDots = () => {
    setDots((d) => (d.length < 3 ? `${d}.` : ""));
  };

  onMount(() => {
    intervalId = globalThis.setInterval(updateDots, 333);
  });

  onCleanup(() => {
    if (intervalId) {
      clearInterval(intervalId);
    }
  });

  return (
    <div class={cn("text-center text-2xl", props.class)}>
      {props.message}
      {dots()}
    </div>
  );
}
