// client/src/components/charts/StackedAreaChart.tsx
import type { HistoryChartMetric, HistoryPoint } from "../../lib/types";
import { createMemo, Show, For } from "solid-js";
import { VisXYContainer, VisArea, VisLine, VisAxis, VisCrosshair, VisTooltip } from "@unovis/solid";
import { CurveType, Line } from "@unovis/ts";
import { formatPercentage } from "../../lib/utils";

interface StackedAreaChartProps {
  history: HistoryPoint[];
  stacked?: boolean;
  metric: HistoryChartMetric;
  class?: string;
}

const x = (d: Record<string, number>) => d.date;

const dateFormatter = (timestamp: number | Date) => {
  const timeVal = typeof timestamp === "number" ? timestamp : timestamp.getTime();
  return new Date(timeVal).toLocaleDateString(undefined, {
    month: "short",
    year: "numeric",
  });
};

export function StackedAreaChart(props: StackedAreaChartProps) {
  const isStacked = () => props.stacked !== false && props.metric !== "rank";

  const competitorMeta = createMemo(() => {
    if (!props.history || props.history.length === 0) {
      return [];
    }
    const lastEntry = props.history.at(-1);
    if (!lastEntry) {
      return [];
    }
    const meta = lastEntry.competitors.map((c) => {
      let finalVal = 0;
      if (props.metric === "win") {
        finalVal = c.win_chance;
      } else if (props.metric === "podium") {
        finalVal = c.pod_chance;
      } else if (props.metric === "rank") {
        finalVal = -c.expected_rank;
      }
      return {
        color: c.color ?? "#888888",
        finalVal,
        id: c.id,
        name: c.name,
      };
    });
    meta.sort((a, b) => a.finalVal - b.finalVal);
    return meta;
  });

  const processedData = createMemo(() => {
    if (!props.history || props.history.length === 0) {
      return [];
    }
    return props.history.map((point) => {
      const dataPoint: Record<string, number> = {
        date: new Date(`${point.date}T12:00:00`).getTime(),
      };
      point.competitors.forEach((c) => {
        let val = 0;
        if (props.metric === "win") {
          val = c.win_chance * 100;
        } else if (props.metric === "podium") {
          val = c.pod_chance * 100;
        } else if (props.metric === "rank") {
          val = c.expected_rank;
        }
        dataPoint[c.id] = val;
      });
      return dataPoint;
    });
  });

  const yDomain = createMemo<[number, number]>(() => {
    if (props.metric === "rank") {
      const allRanks = processedData().flatMap((d) => competitorMeta().map((m) => d[m.id]));
      const maxRank = Math.max(...allRanks, 3);
      return [maxRank + 0.5, 1];
    }
    return [0, 100];
  });

  const yTickFormat = (v: number | Date) => {
    const num = typeof v === "number" ? v : v.getTime();
    if (props.metric === "rank") {
      return num.toFixed(1);
    }
    return `${Math.round(num)}%`;
  };

  const yStacked = createMemo(() =>
    competitorMeta().map((meta) => (d: Record<string, number>) => d[meta.id] || 0),
  );

  const yStackedCumulative = createMemo(() => {
    const meta = competitorMeta();
    return meta.map((_, i) => {
      const idsSlice = meta.slice(0, i + 1).map((m) => m.id);
      return (d: Record<string, number>) => {
        let sum = 0;
        for (const id of idsSlice) {
          sum += d[id] || 0;
        }
        return sum;
      };
    });
  });

  const stackedColorAccessor = (_d: unknown, i: number) => competitorMeta()[i]?.color ?? "#888888";

  const tooltipTemplate = (d: Record<string, number>) => {
    const dateVal = new Date(d.date);
    const dateDisplay = dateVal.toLocaleDateString(undefined, {
      month: "long",
      year: "numeric",
    });

    const sortedCompValues = competitorMeta()
      .map((meta) => ({
        name: meta.name,
        color: meta.color,
        value: d[meta.id] ?? 0,
      }))
      .toSorted((a, b) => b.value - a.value);

    return (
      <div class="relative z-50 rounded-md bg-popover p-2 text-sm text-popover-foreground">
        <p class="mb-1 border-b border-border pb-1 font-bold text-foreground">{dateDisplay}</p>
        <For each={sortedCompValues}>
          {(item) => (
            <div class="flex justify-between">
              <div class="flex items-center">
                <span
                  class="mr-2 inline-block h-2.5 w-2.5 rounded-full"
                  style={{ "background-color": item.color }}
                />
                <span>{item.name}</span>
              </div>
              <span class="ml-4 font-semibold">
                {props.metric === "rank" ? item.value.toFixed(2) : formatPercentage(item.value)}
              </span>
            </div>
          )}
        </For>
      </div>
    ) as HTMLElement;
  };

  const crosshairY = createMemo(() => {
    if (isStacked()) {
      return yStackedCumulative();
    }
    return competitorMeta().map((comp) => (d: Record<string, number>) => d[comp.id] || 0);
  });

  return (
    <div class={`h-full w-full ${props.class ?? ""}`}>
      <VisXYContainer data={processedData()} height={300} yDomain={yDomain()}>
        <svg width="0" height="0">
          <defs>
            <For each={competitorMeta()}>
              {(comp) => (
                <linearGradient id={`grad-stack-${comp.id}`} x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stop-color={comp.color} stop-opacity="0.4" />
                  <stop offset="100%" stop-color={comp.color} stop-opacity="0" />
                </linearGradient>
              )}
            </For>
          </defs>
        </svg>
        <Show
          when={isStacked()}
          fallback={competitorMeta().map((comp) => (
            <>
              <VisArea
                x={x}
                y={(d: Record<string, number>) => d[comp.id] || 0}
                color={`url(#grad-stack-${comp.id})`}
                curveType={CurveType.MonotoneX}
              />
              <VisLine
                x={x}
                y={(d: Record<string, number>) => d[comp.id] || 0}
                color={comp.color}
                curveType={CurveType.MonotoneX}
                attributes={{
                  [Line.selectors.line]: {
                    strokeWidth: 2,
                  },
                }}
              />
            </>
          ))}
        >
          <VisArea
            x={x}
            y={yStacked()}
            color={stackedColorAccessor}
            curveType={CurveType.MonotoneX}
            opacity={0.8}
          />
        </Show>
        <VisAxis type="x" tickFormat={dateFormatter} gridLine={false} numTicks={6} />
        <VisAxis type="y" tickFormat={yTickFormat} gridLine={true} />
        <VisCrosshair
          template={tooltipTemplate}
          x={x}
          y={crosshairY()}
          color={stackedColorAccessor}
        />
        <VisTooltip horizontalShift={15} />
      </VisXYContainer>
    </div>
  );
}

// client/src/components/charts/StackedAreaChart.vue
<script setup lang="ts">
import {
  Area,
  Axis,
  type BulletLegendItemInterface,
  CurveType,
  Line,
} from "@unovis/ts";
import { VisArea, VisAxis, VisLine, VisXYContainer } from "@unovis/vue";
import { useMounted } from "@vueuse/core";
import { useId } from "reka-ui";
import { computed, h, ref, watchEffect } from "vue";
import type { HistoryChartMetric, HistoryPoint } from "@/lib/types";
import { ChartCrosshair } from "@/components/ui/chart";
import HistoryTooltip, { type HistoryTooltipProps } from "./HistoryTooltip.vue";

const STACKED_OPACITY = 0.8;

const {
  history,
  stacked = true,
  filterOpacity = 0.2,
  showGradient = true,
  metric,
} = defineProps<{
  history: HistoryPoint[];
  stacked?: boolean;
  filterOpacity?: number;
  showGradient?: boolean;
  metric: HistoryChartMetric;
}>();

const rawId = useId();
const chartRef = computed(() => rawId.replaceAll(":", "-"));
const isMounted = useMounted();

const competitorMeta = computed(() => {
  if (!history?.length) return [];

  const lastEntry = history.at(-1)!;

  const meta = lastEntry.competitors.map((c) => {
    let finalVal = 0;

    if (metric === "win") {
      finalVal = c.win_chance;
    } else if (metric === "podium") {
      finalVal = c.pod_chance;
    } else if (metric === "rank") {
      finalVal = -c.expected_rank;
    }

    return {
      color: c.color!,
      finalVal,
      id: c.id,
      name: c.name,
    };
  });

  meta.sort((a, b) => a.finalVal - b.finalVal);
  return meta;
});

const processedData = computed(() => {
  if (!history?.length) return [];

  return history.map((point) => {
    const dataPoint: Record<string, number> = {
      date: new Date(point.date + "T12:00:00").getTime(),
    };

    point.competitors.forEach((c) => {
      let val = 0;
      if (metric === "win") {
        val = c.win_chance * 100;
      } else if (metric === "podium") {
        val = c.pod_chance * 100;
      } else if (metric === "rank") {
        val = c.expected_rank;
      }
      dataPoint[c.name] = val;
    });

    return dataPoint;
  });
});

const yDomain = computed(() => {
  if (metric === "rank") {
    const allRanks = processedData.value.flatMap((d) =>
      competitorMeta.value.map((m) => d[m.name]),
    );
    const maxRank = Math.max(...allRanks, 3);
    return [maxRank + 0.5, 1];
  }
  return [0, 100];
});

const yTickFormat = (v: number) => {
  if (metric === "rank") return v.toFixed(1);
  return `${Math.round(v)}%`;
};

const x = (d: Record<string, number>) => d.date;

const legendItems = ref<BulletLegendItemInterface[]>([]);
watchEffect(() => {
  legendItems.value = competitorMeta.value.map((meta) => ({
    color: meta.color,
    inactive: false,
    name: meta.name,
  }));
});

const isCategoryActive = (index: number) => !legendItems.value[index]?.inactive;

const yStacked = computed(() => {
  return competitorMeta.value.map((meta, i) => {
    if (!isCategoryActive(i)) return () => 0;
    return (d: Record<string, number>) => d[meta.name];
  });
});

const stackedColorAccessor = computed(() => {
  return (_: unknown, i: number) => competitorMeta.value[i].color;
});

const dateFormatter = (timestamp: number) => {
  return new Date(timestamp).toLocaleDateString(undefined, {
    month: "short",
    year: "numeric",
  });
};

const tooltip = computed(() => {
  const isPercent = metric !== "rank";

  return (tooltipProps: HistoryTooltipProps) =>
    h(HistoryTooltip, {
      ...tooltipProps,
      percent: isPercent,
    });
});
</script>

<template>
  <div
    class="flex h-100 w-full flex-col items-end"
    style="--vis-text-color: #888888; --vis-axis-grid-color: #e5e7eb"
  >
    <VisXYContainer
      v-if="processedData.length > 0"
      :style="{ height: isMounted ? '100%' : 'auto', width: '100%' }"
      :margin="{ left: 25, right: 20 }"
      :data="processedData"
    >
      <svg width="0" height="0">
        <defs>
          <linearGradient
            v-for="(comp, i) in competitorMeta"
            :id="`${chartRef}-color-${i}`"
            :key="comp.id"
            x1="0"
            y1="0"
            x2="0"
            y2="1"
          >
            <stop
              offset="5%"
              :stop-color="comp.color"
              :stop-opacity="showGradient ? 0.4 : 0"
            />
            <stop offset="95%" :stop-color="comp.color" stop-opacity="0" />
          </linearGradient>
        </defs>
      </svg>

      <ChartCrosshair
        :colors="competitorMeta.map((c) => c.color)"
        :items="legendItems"
        index="date"
        :custom-tooltip="tooltip"
      />

      <VisArea
        v-if="stacked && metric !== 'rank'"
        :x="x"
        :y="yStacked"
        :color="stackedColorAccessor"
        :curve-type="CurveType.MonotoneX"
        :opacity="STACKED_OPACITY"
        :attributes="{
          [Area.selectors.area]: (_d: unknown, i: number) => ({
            fill: `url(#${chartRef}-color-${i})`,
          }),
        }"
      />

      <template v-else>
        <template v-for="(comp, i) in competitorMeta" :key="comp.id">
          <VisArea
            :x="x"
            :y="(d: Record<string, number>) => d[comp.name]"
            color="auto"
            :curve-type="CurveType.MonotoneX"
            :attributes="{
              [Area.selectors.area]: {
                fill: `url(#${chartRef}-color-${i})`,
              },
            }"
            :opacity="isCategoryActive(i) ? 1 : filterOpacity"
          />
        </template>

        <template v-for="(comp, i) in competitorMeta" :key="comp.id">
          <VisLine
            :x="x"
            :y="(d: Record<string, number>) => d[comp.name]"
            :color="comp.color"
            :curve-type="CurveType.MonotoneX"
            :attributes="{
              [Line.selectors.line]: {
                opacity: isCategoryActive(i) ? 1 : filterOpacity,
                strokeWidth: 2,
              },
            }"
          />
        </template>
      </template>

      <VisAxis
        type="x"
        :tick-format="dateFormatter"
        :grid-line="false"
        :tick-line="false"
        tick-text-color="var(--vis-text-color)"
        :num-ticks="6"
      />

      <VisAxis
        type="y"
        :tick-line="false"
        :domain-line="false"
        :grid-line="true"
        :domain="yDomain"
        :attributes="{
          [Axis.selectors.grid]: {
            class: 'text-muted',
            stroke: 'var(--vis-axis-grid-color)',
          },
        }"
        tick-text-color="var(--vis-text-color)"
        :tick-format="yTickFormat"
      />
    </VisXYContainer>

    <div
      v-else
      class="flex h-full w-full items-center justify-center text-sm text-muted-foreground"
    >
      No data available
    </div>
  </div>
</template>
