// client/src/components/ui/input.tsx
import { splitProps, type JSX } from "solid-js";
import { cn } from "../../lib/utils";

export interface InputProps extends Omit<
  JSX.InputHTMLAttributes<HTMLInputElement>,
  "onInput" | "onChange" | "value"
> {
  class?: string;
  type?: string;
  value?: string | number | undefined;
  onInput?: (value: string) => void;
  onChange?: (value: string) => void;
}

export function Input(props: InputProps) {
  const [local, others] = splitProps(props, ["class", "type", "value", "onInput", "onChange"]);

  return (
    <input
      type={local.type ?? "text"}
      value={local.value ?? ""}
      onInput={(e) => {
        local.onInput?.(e.currentTarget.value);
      }}
      onChange={(e) => {
        local.onChange?.(e.currentTarget.value);
      }}
      class={cn(
        "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50",
        local.class,
      )}
      {...others}
    />
  );
}

// client/src/components/ui/input/Input.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { useVModel } from "@vueuse/core";
import { cn } from "@/lib/utils";

const props = defineProps<{
  defaultValue?: string | number;
  modelValue?: string | number;
  class?: HTMLAttributes["class"];
}>();

const emits = defineEmits<{
  (e: "update:modelValue", payload: string | number): void;
}>();

const modelValue = useVModel(props, "modelValue", emits, {
  passive: true,
  defaultValue: props.defaultValue,
});
</script>

<template>
  <input
    v-model="modelValue"
    :class="
      cn(
        'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50',
        props.class,
      )
    "
  />
</template>
