// client/src/components/ui/label.tsx
import type { JSX } from "solid-js";
import { cn } from "../../lib/utils";

export function Label(props: JSX.LabelHTMLAttributes<HTMLLabelElement>) {
  return (
    <label
      class={cn(
        "text-sm leading-none font-medium peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
        props.class,
      )}
      for={props.for}
      {...props}
    >
      {props.children}
    </label>
  );
}

// client/src/components/ui/label/Label.vue
<script setup lang="ts">
import { Label, type LabelProps } from "radix-vue";
import { type HTMLAttributes, computed } from "vue";
import { cn } from "@/lib/utils";

const props = defineProps<LabelProps & { class?: HTMLAttributes["class"] }>();

const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props;

  return delegated;
});
</script>

<template>
  <Label
    v-bind="delegatedProps"
    :class="
      cn(
        'text-sm leading-none font-medium peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
        props.class,
      )
    "
  >
    <slot />
  </Label>
</template>
