// client/src/components/custom/CompetitorDropdown.vue
<script setup lang="ts">
import IndividualHistogram from "@/components/charts/IndividualHistogram.vue";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  CompetitorSimulationResult,
  eventAttempts,
  SupportedWCAEvent,
} from "@/lib/types";
import { formatPercentage } from "@/lib/utils";
import { CircleAlert } from "lucide-vue-next";
import { computed, ref } from "vue";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "../ui/collapsible";
import ColoredCircle from "./ColoredCircle.vue";
import CompetitorLink from "./CompetitorLink.vue";
import FMCEntryField from "./FMCEntryField.vue";
import Chevron from "./RotatableChevron.vue";
import ResultEntryField from "./TimeEntryField.vue";

const lowDataWarningThreshold = 12 as const;

const { result, color, event } = defineProps<{
  result: CompetitorSimulationResult;
  color: string;
  event: SupportedWCAEvent;
}>();

const model = defineModel<number[]>({ required: true });

const isOpen = ref<boolean>(false);

const winPercentage = computed(() => formatPercentage(result.win_chance * 100));
const podiumPercentage = computed(() =>
  formatPercentage(result.pod_chance * 100),
);
const expectedRank = computed(() => result.expected_rank.toFixed(4));

const ariaId = computed(() => `dropdown-${result.id}`);
</script>

<template>
  <Collapsible v-model:open="isOpen">
    <CollapsibleTrigger as-child :aria-controls="ariaId">
      <div role="button" tabindex="0" :aria-label="`Details for ${result.id}`"
        class="hover:bg-secondary focus-visible:bg-secondary flex w-full cursor-pointer justify-between rounded-md border-0 bg-transparent p-2 ps-1 text-left focus:outline-none">
        <div class="flex-[2] lg:flex-[1.5] min-w-0 text-left">
          <div class="flex flex-row">
            <div class="mx-2 flex flex-col justify-center">
              <ColoredCircle :color />
            </div>
            <CompetitorLink :name="result.name" :id="result.id" :iso2="result.country_iso2" :event="event"
              class="me-1 flex items-center gap-1" />
            <TooltipProvider :delayDuration="250" v-if="result.sample_size < lowDataWarningThreshold">
              <Tooltip>
                <TooltipTrigger aria-label="Low result warning tooltip">
                  <CircleAlert class="ms-1 scale-75 text-red-600" />
                </TooltipTrigger>
                <TooltipContent>
                  Competitor only has performed
                  {{ result.sample_size }} solves since date cutoff.
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
        </div>
        <div class="flex-1 text-center">
          {{ winPercentage }}
        </div>
        <div class="flex-1 text-center">
          {{ podiumPercentage }}
        </div>
        <div class="flex-1 text-center">
          {{ expectedRank }}
        </div>
        <Chevron :up="isOpen" />
      </div>
    </CollapsibleTrigger>
    <CollapsibleContent class="space-y-2" :id="ariaId">
      <IndividualHistogram :color="color" :data="result.histogram" :event />
      <div class="flex flex-col items-center px-2 lg:ms-2 lg:flex-row lg:gap-4">
        <div v-for="attemptIdx in eventAttempts[event]" v-bind:key="attemptIdx"
          class="mb-2 flex items-center gap-2 lg:mb-0">
          <span class="whitespace-nowrap">Attempt {{ attemptIdx }}:</span>
          <div class="lg:max-w-24">
            <ResultEntryField v-if="event != '333fm'" v-model="model[attemptIdx - 1]" />
            <FMCEntryField v-else v-model="model[attemptIdx - 1]" />
          </div>
        </div>
      </div>
      <hr class="mx-2" />
    </CollapsibleContent>
  </Collapsible>
</template>

// client2/src/components/custom/CompetitorDropdown.tsx
import { createSignal, Show, Index } from "solid-js";
import { CircleAlert } from "lucide-solid";
import {
  type CompetitorSimulationResult,
  type SupportedWCAEvent,
  eventAttempts,
} from "../../lib/types";
import { formatPercentage } from "../../lib/utils";
import { IndividualHistogram } from "../charts/IndividualHistogram";
import { ColoredCircle } from "./ColoredCircle";
import { CompetitorLink } from "./CompetitorLink";
import { FMCEntryField } from "./FMCEntryField";
import { RotatableChevron } from "./RotatableChevron";
import { TimeEntryField } from "./TimeEntryField";

interface CompetitorDropdownProps {
  result: CompetitorSimulationResult;
  color: string;
  event: SupportedWCAEvent;
  value: number[];
  onChange: (val: number[]) => void;
}

export function CompetitorDropdown(props: CompetitorDropdownProps) {
  const [isOpen, setIsOpen] = createSignal(false);
  const lowDataWarningThreshold = 12;

  const winPercentage = () => formatPercentage(props.result.win_chance * 100);
  const podiumPercentage = () => formatPercentage(props.result.pod_chance * 100);
  const expectedRank = () => props.result.expected_rank.toFixed(4);

  return (
    <div class="border-b py-2 last:border-b-0">
      <button
        type="button"
        onClick={() => setIsOpen(!isOpen())}
        aria-label={`Details for ${props.result.id}`}
        class="flex w-full items-center justify-between rounded-md p-2 ps-1 text-left transition-colors hover:bg-secondary focus:outline-none focus-visible:bg-secondary"
      >
        <div class="flex min-w-0 flex-[2] items-center gap-3 lg:flex-[1.5]">
          <ColoredCircle color={props.color} class="ms-2 shrink-0" />

          <CompetitorLink
            name={props.result.name}
            id={props.result.id}
            iso2={props.result.country_iso2}
            event={props.event}
            class="flex items-center truncate text-sm font-medium text-foreground hover:underline"
          />

          <Show when={props.result.sample_size < lowDataWarningThreshold}>
            <span
              title={`Competitor only has performed ${props.result.sample_size} solves since date cutoff.`}
              class="cursor-help text-destructive"
              aria-label="Low result warning"
            >
              <CircleAlert class="h-4 w-4" />
            </span>
          </Show>
        </div>
        <div class="flex-1 text-center text-sm text-foreground">{winPercentage()}</div>
        <div class="flex-1 text-center text-sm text-foreground">{podiumPercentage()}</div>
        <div class="flex-1 text-center text-sm text-foreground">{expectedRank()}</div>
        <RotatableChevron up={isOpen()} />
      </button>

      <Show when={isOpen()}>
        <div class="mt-1 space-y-4 rounded-md px-2 py-3 duration-200 animate-in fade-in-0">
          <IndividualHistogram
            color={props.color}
            data={props.result.histogram}
            event={props.event}
          />

          <div class="flex flex-wrap items-center gap-2 px-2 lg:ms-2 lg:gap-4">
            <Index each={Array.from({ length: eventAttempts[props.event] })}>
              {(_, idx) => (
                <div class="flex items-center gap-2">
                  <span class="text-xs whitespace-nowrap text-muted-foreground">
                    Attempt {idx + 1}:
                  </span>
                  <div class="max-w-24">
                    <Show
                      when={props.event !== "333fm"}
                      fallback={
                        <FMCEntryField
                          value={props.value[idx] ?? 0}
                          onChange={(val) => {
                            const updated = [...props.value];
                            updated[idx] = val;
                            props.onChange(updated);
                          }}
                        />
                      }
                    >
                      <TimeEntryField
                        value={props.value[idx] ?? 0}
                        onChange={(val) => {
                          const updated = [...props.value];
                          updated[idx] = val;
                          props.onChange(updated);
                        }}
                      />
                    </Show>
                  </div>
                </div>
              )}
            </Index>
          </div>
        </div>
      </Show>
    </div>
  );
}
