// client/src/components/custom/FMCEntryField.vue
<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { Input } from "@/components/ui/input";

const model = defineModel<number>({ required: true });
const inputValue = ref("");

const formatInput = (input: string): string => {
  const number = parseInt(input.replaceAll(/\D/g, ""));
  if (isNaN(number) || number === 0) return "";

  return number.toString();
};

const toValue = (input: string): number => {
  if (input === "") return 0;
  if (input.toLowerCase() === "dnf") return -1;

  const digits = input.replaceAll(/\D/g, "");
  if (!digits) return 0;

  return parseInt(digits);
};

const updateInputFromModel = (value: number) => {
  if (value === -1) {
    inputValue.value = "DNF";
  } else if (value === 0) {
    inputValue.value = "";
  } else {
    const formatted = value.toString();
    inputValue.value = formatted;
  }
};

onMounted(() => updateInputFromModel(model.value));

watch(() => model.value, updateInputFromModel, { flush: "post" });

watch(inputValue, (value) => {
  if (value === "DNF") {
    model.value = -1;
  } else {
    const formattedInput = formatInput(value);
    inputValue.value = formattedInput;
    model.value = toValue(formattedInput);
  }
});

const handleKeydown = (event: KeyboardEvent) => {
  if (["d", "D"].includes(event.key)) {
    event.preventDefault();
    inputValue.value = "DNF";
    model.value = -1;
  }
};
</script>

<template>
  <Input
    class="min-w-[50vw] lg:min-w-0"
    v-model="inputValue"
    @keydown="handleKeydown"
  />
</template>

// client2/src/components/custom/FMCEntryField.tsx
import { createSignal, createEffect } from "solid-js";
import { toInt } from "../../lib/utils";
import { Input } from "../ui/input";

interface FMCEntryFieldProps {
  value: number;
  onChange: (val: number) => void;
}

const formatInput = (input: string): string => {
  const number = toInt(input.replaceAll(/\D/gu, ""));
  if (number === null || number === 0) {
    return "";
  }
  return number.toString();
};

const toValue = (input: string): number => {
  if (input === "") {
    return 0;
  }
  if (input.toLowerCase() === "dnf") {
    return -1;
  }

  const digits = input.replaceAll(/\D/gu, "");
  if (!digits) {
    return 0;
  }

  return toInt(digits, 0);
};

export function FMCEntryField(props: FMCEntryFieldProps) {
  const [inputValue, setInputValue] = createSignal("");

  const updateInputFromModel = (value: number) => {
    if (value === -1) {
      setInputValue("DNF");
    } else if (value === 0) {
      setInputValue("");
    } else {
      setInputValue(value.toString());
    }
  };

  createEffect(() => {
    updateInputFromModel(props.value);
  });

  const handleInput = (val: string) => {
    if (val === "DNF") {
      setInputValue("DNF");
      props.onChange(-1);
    } else {
      const formattedInput = formatInput(val);
      setInputValue(formattedInput);
      props.onChange(toValue(formattedInput));
    }
  };

  const handleKeydown = (event: KeyboardEvent) => {
    if (["d", "D"].includes(event.key)) {
      event.preventDefault();
      setInputValue("DNF");
      props.onChange(-1);
    }
  };

  return (
    <Input
      class="h-9 min-w-[50vw] lg:min-w-0"
      value={inputValue()}
      onInput={handleInput}
      onKeyDown={handleKeydown}
    />
  );
}
